service: pdf

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

custom: 
  serverless-offline:
    location: .webpack/service
  bundle:
    sourcemaps: false  
    copyFiles:                       
      - from: 'node_modules/chrome-aws-lambda/bin/aws.tar.br'
        to: './bin' 
      - from: 'node_modules/chrome-aws-lambda/bin/chromium.br'
        to: './bin'   
      - from: 'node_modules/chrome-aws-lambda/bin/swiftshader.tar.br'
        to: './bin'   
provider: 
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: test
  apiGateway: 
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'
  tracing:
    apiGateway: true
    lambda: true
functions:
  downloadPdf:
    handler: lambdas/download-pdf.main
    events:
      - http:
          path: download-pdf
          method: get
          cors: true
    timeout: 180